name: Deploy to AWS Lightsail Container

on:
  push:
    branches:
      - main

permissions:
  id-token: write # This is needed for AWS CLI login
  contents: read # This is needed for the checkout action

jobs:
  deploy:
    name: Deploy to AWS Lightsail Container
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install required packages
        run: |
          sudo apt-get update
          sudo apt-get install -y jq unzip

      - name: Install AWS CLI
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install || true
          aws --version

      - name: Build Docker Image
        run: |
          docker build -t article-github-actions-lightsail:release .

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ap-southeast-1

      - name: Push image to AWS Lightsail
        env:
          DATE_TIME: ${{ github.event.repository.updated_at }}
        run: |
          aws lightsail push-container-image \
           --region ap-southeast-1 \
           --service-name article-github-actions-lightsail \
           --label ${{ env.DATE_TIME }}-release 
           --image article-github-actions-lightsail:release

      - name: Deploy to AWS Lightsail
        run: |
          aws lightsail get-container-images \
           --service-name article-github-actions-lightsail \
           --output json | jq --raw-output ".containerImages[0].image" > image.txt

          jq --arg image "$(cat image.txt)" '.containers.app.image = $image' task-definition.json > task-definition-deploy.json

          aws lightsail create-container-service-deployment \
           --service-name article-github-actions-lightsail \
           --cli-input-json file://$(pwd)/task-definition-deploy.json
